name: Build image with FS preloaded data

on:
  workflow_dispatch:
    inputs:
      push_slim:
        description: 'Pousser lâ€™image avec FS preloaded sur GHCR ?'
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build-slim:
    runs-on: ubuntu-latest

    steps:
    - name: Free disk space
      run: |
        df -h
        docker system df || true
        docker builder prune -af || true
        docker system prune -af --volumes || true
        sudo rm -rf /usr/local/lib/android || true
        sudo rm -rf /opt/ghc || true
        sudo rm -rf /usr/share/dotnet || true
        sudo rm -rf /usr/local/.ghcup || true
        df -h

    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/bastienird/tunaatlas_pie_map_shiny-fsdata-preloaded
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
        labels: |
          org.opencontainers.image.title=GlobalTunaAtlasExplorer
          org.opencontainers.image.description=Interactive Shiny application for Tuna Atlas data visualization with FS preloaded data
          org.opencontainers.image.vendor=IRD
          org.opencontainers.image.author=Bastien Grasset <bastien.grasset@ird.fr>
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build & push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.fsdata
        push: ${{ inputs.push_slim }}
        provenance: false
        sbom: false
        tags: |
          ghcr.io/bastienird/tunaatlas_pie_map_shiny-fsdata-preloaded:latest
          ghcr.io/bastienird/tunaatlas_pie_map_shiny-fsdata-preloaded:${{ github.sha }}

    - name: Inspect remote manifest
      run: docker buildx imagetools inspect ghcr.io/bastienird/tunaatlas_pie_map_shiny-fsdata-preloaded:latest
